## Support Vector Regression

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
path=path=r'https://drive.google.com/uc?export=download&id=16QxJJ2FWQHNULLzrNVBmEdzTVls6iq5e'
df=pd.read_csv(path)

In [ ]:
df.head()

Price  Area  No. of Bedrooms  ...  Gas Connection  Jogging Track  Swimming Pool
0  4850000   720                1  ...               0              0              0
1  4500000   600                1  ...               0              1              1
2  6700000   650                1  ...               0              1              1
3  4500000   650                1  ...               0              0              0
4  5000000   665                1  ...               0              0              0

[5 rows x 17 columns]

In [ ]:
X=df.drop('Price',axis=1)
y=df['Price']
print('Shape of X= ',X.shape)
print('Shape of y= ',y.shape)

Shape of X=  (6347, 16)
Shape of y=  (6347,)


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=52) #we need 20 percent test data
print('Shape of X_train= ',X_train.shape)
print('Shape of y_train= ',y_train.shape)
print('Shape of X_test= ',X_test.shape)
print('Shape of y_test= ',y_test.shape)

Shape of X_train=  (5077, 16)
Shape of y_train=  (5077,)
Shape of X_test=  (1270, 16)
Shape of y_test=  (1270,)


In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train_sc=sc.transform(X_train)
X_test_sc=sc.transform(X_test)

In [ ]:
from sklearn.svm import SVR

In [ ]:
svr_rbf=SVR(kernel='rbf')
svr_rbf.fit(X_train,y_train)
svr_rbf.score(X_test,y_test)

-0.09475672722582296

In [ ]:
svr_linear=SVR(kernel='linear')
svr_linear.fit(X_train,y_train)
svr_linear.score(X_test,y_test)

0.39279102691835144

In [ ]:
svr_poly=SVR(kernel='poly',degree=2)
svr_poly.fit(X_train,y_train)
svr_poly.score(X_test,y_test)

-0.09445037893796981

In [ ]:
#predict the value of home
y_predict=svr_linear.predict(X_test)
y_predict

array([15035955.26451304, 17382657.40149016,  1271809.36930234, ...,
       13004582.00431244,  9676939.51891618, 13880153.41043124])

In [ ]:
y_test

3022    11000000
1469    24500000
3101     3900000
3527    13500000
2172     6500000
          ...   
1330     4100000
6270     6500000
2458    10000000
4313     5300000
3322    10000000
Name: Price, Length: 1270, dtype: int64

In [ ]:
#to check for error
from sklearn.metrics import mean_squared_error #mostly mean squared error (cost function is used)
mse=mean_squared_error(y_test,y_predict)
rmse=np.sqrt(mse) #to convert mean squared error into square root
print('Mean Squared Error= ',mse)
print('Root Mean Squared Error= ',rmse)

Mean Squared Error=  218183988831748.84
Root Mean Squared Error=  14771052.394184675


In [ ]:
#this shows not best model

Support Vector Classification Alorithm

In [ ]:
from sklearn.datasets import load_breast_cancer
data=load_breast_cancer()

In [ ]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
data.feature_names

In [ ]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
#create dataframe
df=pd.DataFrame(np.c_[data.data,data.target], columns=[list(data.feature_names)+['target']])
df.head()

mean radius mean texture  ... worst fractal dimension target
0       17.99        10.38  ...                 0.11890    0.0
1       20.57        17.77  ...                 0.08902    0.0
2       19.69        21.25  ...                 0.08758    0.0
3       11.42        20.38  ...                 0.17300    0.0
4       20.29        14.34  ...                 0.07678    0.0

[5 rows x 31 columns]

In [ ]:
df.shape

(569, 31)

In [ ]:
#Split Data
x=df.iloc[:, 0:-1]
y=df.iloc[:, -1]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=52) #we need 20 percent test data
print('Shape of X_train= ',X_train.shape)
print('Shape of y_train= ',y_train.shape)
print('Shape of X_test= ',X_test.shape)
print('Shape of y_test= ',y_test.shape)

Shape of X_train=  (455, 30)
Shape of y_train=  (455,)
Shape of X_test=  (114, 30)
Shape of y_test=  (114,)


In [ ]:
from sklearn.svm import SVC

In [ ]:
classification_rbf=SVC(kernel='rbf')
classification_rbf.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
classification_rbf.score(X_test,y_test)

0.9649122807017544

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train_sc=sc.transform(X_train)
X_test_sc=sc.transform(X_test)

In [ ]:
classification_rbf_2=SVC(kernel='rbf')
classification_rbf_2.fit(X_train_sc,y_train)
classification_rbf_2.score(X_test_sc,y_test)

0.9912280701754386

In [ ]:
#This shows that after feature scaling, more accuracy in Support Vector Machine Algorithms

In [ ]:
#SVC with kernal Polynomial
classification_poly=SVC(kernel='poly',degree=2)
classification_poly.fit(X_train_sc,y_train)
classification_poly.score(X_test_sc,y_test)

0.8771929824561403

In [ ]:
#this shows less accuracy in case of svs polynomial

In [ ]:
#SVC with kernal Polynomial
classification_linear=SVC(kernel='linear')
classification_linear.fit(X_train_sc,y_train)
classification_linear.score(X_test_sc,y_test)

0.9736842105263158

In [ ]:
#Thus greater accuracy in case of rbf

## Predict Cancer

In [ ]:
#take supposed patient data
patient1=[17.99,10.38,122.8,1001.0,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04984,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189]

In [ ]:
patient1=np.array([patient1]) #to convert list into 2d array
patient1

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.984e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])

In [ ]:
classification_rbf_2.predict(patient1)

array([0.])

In [ ]:
#OR

In [ ]:
#feature scale the data
patient1_sc=sc.transform(np.array([patient1])) #convert into array
patient1_sc

array([[ 1.12815116, -2.0804069 ,  1.30662032,  1.01757653,  1.59589974,
         3.29463074,  2.69542418,  2.60536672,  2.27698091,  2.22271631,
         2.41916963, -0.58102452,  2.74151249,  2.37536117, -0.20258603,
         1.34730883,  0.69402461,  0.65162277,  1.26176645,  0.86412334,
         1.88719722, -1.35739373,  2.30608673,  1.9847149 ,  1.27218482,
         2.54149815,  2.04932679,  2.3093538 ,  2.72850956,  1.83478293]])

In [ ]:
#give this data to model
classification_rbf_2.predict(patient1_sc)

array([0.])

In [ ]:
#this shows that patient has cancer

In [ ]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
#OR
pred=classification_rbf_2.predict(patient1_sc)

In [ ]:
if pred[0]==0:
  print('Patient has cancer (malignant tumor)')
else:
  print('Patient has no cancer (malignant benign)')

Patient has cancer (malignant tumor)
