In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1 - Linear Regression Exercise1

In [2]:
df=pd.read_csv('Linear Regression Exercise 1.csv')
df.head(3)

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000

In [3]:
df.describe()

area  bedrooms       age          price
count     5.000000  4.000000   5.00000       5.000000
mean   3280.000000  3.750000  18.20000  616000.000000
std     540.370243  0.957427   8.01249   83919.604384
min    2600.000000  3.000000   8.00000  550000.000000
25%    3000.000000  3.000000  15.00000  565000.000000
50%    3200.000000  3.500000  18.00000  595000.000000
75%    3600.000000  4.250000  20.00000  610000.000000
max    4000.000000  5.000000  30.00000  760000.000000

## Handling Missing Values in the feature of 'bedrooms'

In [4]:
df1=df.copy()

In [5]:
df1.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [6]:
df1.bedrooms=df1['bedrooms'].fillna(df.bedrooms.median())
df1

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.5   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(df1[['area','bedrooms','age']],df1.price)

LinearRegression()

In [8]:
lr.coef_

array([    198.47159002, -116583.73881651,  -14267.77585936])

In [9]:
lr.intercept_

656046.5390048662

In [10]:
lr.predict([[3000,3,30]])

C:\Users\Admin\anaconda3\envs\A\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([473676.81682624])

In [11]:
lr.predict([[2500,4,40]])

C:\Users\Admin\anaconda3\envs\A\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([115179.52440747])

## To convert words to numbers

In [12]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [13]:
from word2number import w2n

In [14]:
a=w2n.word_to_num("two million three thousand nine hundred and eighty four")
a

2003984

In [15]:
w2n.word_to_num('two point three')

2.3

In [16]:
w2n.word_to_num('112')

112

In [17]:
w2n.word_to_num('point one')

0.1

# 2 - Linear Regression Exercise 2

In [43]:
df2=pd.read_csv('Linear Regression Exercise 2.csv')
df2.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [44]:
df2.shape

(8, 4)

In [53]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  6 non-null      object 
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 384.0+ bytes


## Handling NaN Values

In [46]:
df2.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [47]:
df2.keys()

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

<b> Changing Column names for easy working

In [72]:
df2['test_score']=df2['test_score(out of 10)']
df2['salary']=df2['salary($)']
df2['interview_score']=df2['interview_score(out of 10)']

In [73]:
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0        NaN                    8.0                           9      50000   
1        NaN                    8.0                           6      45000   
2       five                    6.0                           7      60000   
3        two                   10.0                          10      65000   
4      seven                    9.0                           6      70000   
5      three                    7.0                          10      62000   
6        ten                    NaN                           7      72000   
7     eleven                    7.0                           8      80000   

   test_score  interview_score  salary  
0         8.0                9   50000  
1         8.0                6   45000  
2         6.0                7   60000  
3        10.0               10   65000  
4         9.0                6   70000  
5         7.0               10   62000  
6         NaN                7   72000  
7         7.0                8   80000

<b> Dropping the previous columns whose names have been changed

In [74]:
df3=df2.drop(['test_score(out of 10)','interview_score(out of 10)','salary($)'],axis='columns')
df3

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

### Handling NaN values of feature 'test_score'

In [75]:
df3.test_score=df3['test_score'].fillna(df3.test_score.median())
df3

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

## Handling NaN values of feature 'experience'

In [76]:
df3.experience=df3.experience.fillna('zero')  #Replacing NaN values with 'zero' string
df3

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

## To apply Word2Number function on feature 'experience'

In [77]:
df3.experience=df3.experience.apply(w2n.word_to_num)
df3

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

## Replacing '0' values in column 'experience' with 'median' of the values in column 'experience'

In [85]:
df4=df3.replace({'experience':0},df3.median())
df4

experience  test_score  interview_score  salary
0         4.0         8.0                9   50000
1         4.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         8.0                7   72000
7        11.0         7.0                8   80000

## Model Building

In [81]:
lr_2=LinearRegression()
lr_2.fit(df4[['experience','test_score','interview_score']],df4.salary)

LinearRegression()

In [82]:
lr_2.coef_

array([3390.87422644, 1803.45158198, 3184.69450013])

In [84]:
lr_2.intercept_

4220.8228013597545

In [87]:
lr_2.predict([[2,9,8]])

C:\Users\Admin\anaconda3\envs\A\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([52711.19149307])

In [89]:
lr_2.predict([[20,9,9]])

C:\Users\Admin\anaconda3\envs\A\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([116931.62206921])