In [ ]:
#We use structure called as LSTM RNN to solve vanishing gradient and exploding gradient problems when we update weights in backpropagation.

In [ ]:
#Our RNN suffers short time memory problem, LSTM RNN solves this short memory problem (e.g. Today, due to my current job situation and family conditions, I need to take an action. To predict word need, it needs to know word today.Because of vanishing gradient problems, traditional rnn have short time memory.so they don't remeber which word appeared in beginning.To rember long time memory, we need to indroduce long time memory LSTM RNN)
#Memory cell is used for remembering and forgettig based on the context of input. As the context of statement changes,some of the previous information it should remeber and also be able to new information.

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
#sentences
sent=['the glass of milk',
      'the cup of tea',
      'he is a good boy',
      'I am Faseeh Ur Rehman']

In [ ]:
sent

['the glass of milk',
 'the cup of tea',
 'he is a good boy',
 'I am Faseeh Ur Rehman']

In [ ]:
#vocabulary size
voc_size=1000

## One Hot Representation

In [ ]:
onehot_repr=[one_hot(words, voc_size)for words in sent]
print(onehot_repr)

[[710, 140, 710, 132], [710, 801, 710, 952], [35, 627, 279, 35, 242], [733, 960, 864, 465, 527]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 710 140 710 132]
 [  0   0   0   0 710 801 710 952]
 [  0   0   0  35 627 279  35 242]
 [  0   0   0 733 960 864 465 527]]


In [ ]:
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             10000     
Total params: 10,000
Trainable params: 10,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

[[[ 0.03086385 -0.01594454 -0.00343667 -0.01774197  0.00630287
    0.00609045  0.00497197  0.03956093  0.0031427   0.04009655]
  [ 0.03086385 -0.01594454 -0.00343667 -0.01774197  0.00630287
    0.00609045  0.00497197  0.03956093  0.0031427   0.04009655]
  [ 0.03086385 -0.01594454 -0.00343667 -0.01774197  0.00630287
    0.00609045  0.00497197  0.03956093  0.0031427   0.04009655]
  [ 0.03086385 -0.01594454 -0.00343667 -0.01774197  0.00630287
    0.00609045  0.00497197  0.03956093  0.0031427   0.04009655]
  [ 0.0048113  -0.03782547 -0.03903252  0.00484579  0.02703295
    0.00273655  0.02168695  0.03333605 -0.00562031  0.00935534]
  [ 0.02901936  0.04543563 -0.03695554 -0.00583567 -0.03225058
    0.01679722  0.00350072 -0.00636773  0.02998208 -0.04091451]
  [ 0.0048113  -0.03782547 -0.03903252  0.00484579  0.02703295
    0.00273655  0.02168695  0.03333605 -0.00562031  0.00935534]
  [ 0.04684515  0.01640785  0.03967712  0.03187178  0.00926591
   -0.02188549 -0.02094936 -0.04418519  0.013625

In [ ]:
embedded_docs[0]

array([  0,   0,   0,   0, 710, 140, 710, 132], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

[[ 0.03086385 -0.01594454 -0.00343667 -0.01774197  0.00630287  0.00609045
   0.00497197  0.03956093  0.0031427   0.04009655]
 [ 0.03086385 -0.01594454 -0.00343667 -0.01774197  0.00630287  0.00609045
   0.00497197  0.03956093  0.0031427   0.04009655]
 [ 0.03086385 -0.01594454 -0.00343667 -0.01774197  0.00630287  0.00609045
   0.00497197  0.03956093  0.0031427   0.04009655]
 [ 0.03086385 -0.01594454 -0.00343667 -0.01774197  0.00630287  0.00609045
   0.00497197  0.03956093  0.0031427   0.04009655]
 [ 0.0048113  -0.03782547 -0.03903252  0.00484579  0.02703295  0.00273655
   0.02168695  0.03333605 -0.00562031  0.00935534]
 [ 0.02901936  0.04543563 -0.03695554 -0.00583567 -0.03225058  0.01679722
   0.00350072 -0.00636773  0.02998208 -0.04091451]
 [ 0.0048113  -0.03782547 -0.03903252  0.00484579  0.02703295  0.00273655
   0.02168695  0.03333605 -0.00562031  0.00935534]
 [ 0.04684515  0.01640785  0.03967712  0.03187178  0.00926591 -0.02188549
  -0.02094936 -0.04418519  0.01362551  0.00665518]]